{% set version = '0.2-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcpptn
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppTN_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppTN/RcppTN_{{ version }}.tar.gz
  sha256: aefaabe4fb0a9b0c895ea4ca77f36b6a3522d6f316e347b429bb7f176c615c54

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ stdlib('c') }}  # [not win]
    - {{ stdlib('m2w64_c') }}  # [win]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp

test:
  commands:
    - $R -e "library('RcppTN')"           # [not win]
    - "\"%R%\" -e \"library('RcppTN')\""  # [win]

about:
  home: http://github.com/olmjo/RcppTN
  license: GPL-2.0-or-later
  summary: R-level and C++-level functionality to generate random deviates from and calculate
    moments of a Truncated Normal distribution using the algorithm of Robert (1995)
    <DOI:10.1007/BF00143942>. In addition to RNG, functions for calculating moments,
    densities, and entropies are provided at both levels.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: RcppTN
# Type: Package
# Title: Rcpp-Based Truncated Normal Distribution RNG and Family
# Version: 0.2-2
# Date: 2017-11-21
# Authors@R: c(person("Jonathan", "Olmsted", role = c("aut", "cre"), email = "jpolmsted@gmail.com"))
# Author: Jonathan Olmsted [aut, cre]
# Maintainer: Jonathan Olmsted <jpolmsted@gmail.com>
# Description: R-level and C++-level functionality to generate random deviates from and calculate moments of a Truncated Normal distribution using the algorithm of Robert (1995) <DOI:10.1007/BF00143942>. In addition to RNG, functions for calculating moments, densities, and entropies are provided at both levels.
# URL: http://github.com/olmjo/RcppTN
# BugReports: http://github.com/olmjo/RcppTN/issues
# License: GPL (>= 2)
# Depends:
# Suggests: testthat
# LinkingTo: Rcpp
# Imports: Rcpp
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-11-21 10:36:54 UTC; olmjo
# Repository: CRAN
# Date/Publication: 2017-11-21 11:42:30 UTC
